apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    meta.helm.sh/release-name: release
    meta.helm.sh/release-namespace: times
    prometheus.io/port: "9187"
    prometheus.io/scrape: "true"
  creationTimestamp: "2023-03-17T04:32:24Z"
  labels:
    app: timescaledb-single-chart
    app.kubernetes.io/component: postgres-exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-timescaledb
    app.kubernetes.io/version: 0.2.17
    chart: timescaledb-0.2.17
    cluster-name: timescaledb-single-chart
    component: postgres-exporter
    heritage: Helm
    release: release
  name: timescaledb-single-chart-prometheus
  namespace: times
  resourceVersion: "25841955"
  uid: fcb00193-ff76-497f-a62f-48ee414b5067
spec:
  clusterIP: 10.108.17.74
  clusterIPs:
  - 10.108.17.74
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 9187
    protocol: TCP
    targetPort: pg-exporter
  selector:
    app: timescaledb-single-chart
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
