apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    meta.helm.sh/release-name: release
    meta.helm.sh/release-namespace: times
  creationTimestamp: "2023-03-17T04:32:24Z"
  labels:
    app: timescaledb-single-chart
    app.kubernetes.io/component: postgres
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: release-timescaledb
    app.kubernetes.io/version: 0.2.17
    chart: timescaledb-0.2.17
    cluster-name: timescaledb-single-chart
    component: postgres
    heritage: Helm
    release: release
    role: replica
  name: timescaledb-single-chart-replica
  namespace: times
  resourceVersion: "25745967"
  uid: 0fe7224f-7f49-4923-9b51-30bc5e452d42
spec:
  clusterIP: 10.108.27.25
  clusterIPs:
  - 10.108.27.25
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app: timescaledb-single-chart
    cluster-name: timescaledb-single-chart
    role: replica
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
