apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-replicaset-chart
  labels:
    app: prometheus-redis-exporter
    name: redis-exporter-prometheus-redis-exporter
  namespace: gmp-test
spec:
  endpoints:
  - interval: 30s
    port: redis-exporter
  namespaceSelector:
    matchNames:
    - redis
  selector:
    matchLabels:
      app: prometheus-redis-exporter
